"""Parsers for Sentinel-1 GRD annotation files.

A GRD product ships three XML files per polarisation that matter here:

* ``annotation/<pol>.xml``            - product metadata and the geolocation grid
* ``annotation/calibration/calibration-<pol>.xml`` - radiometric calibration LUTs
* ``annotation/calibration/noise-<pol>.xml``       - thermal noise LUTs

All LUTs are sparse (one vector every few hundred lines, one sample every
~40 pixels) and are bilinearly interpolated onto the image grid, as described
in the ESA document "Thermal Denoising of Products Generated by the S-1 IPF"
(MPC-0392) and the S-1 Level-1 product specification.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from dataclasses import dataclass, field

import numpy as np
from scipy.interpolate import LinearNDInterpolator, RectBivariateSpline


def _floats(text: str | None) -> np.ndarray:
    return np.array((text or "").split(), dtype=np.float64)


def _interp_rows(rows: np.ndarray, lines: np.ndarray, table: np.ndarray) -> np.ndarray:
    """Linearly interpolate ``table`` (one row per entry of ``lines``) at ``rows``.

    Values outside ``lines`` are clamped to the first/last vector, which is how
    the IPF treats the image edges.
    """
    if len(lines) == 1:
        return np.repeat(table, len(rows), axis=0)
    i = np.clip(np.searchsorted(lines, rows, side="right") - 1, 0, len(lines) - 2)
    w = np.clip((rows - lines[i]) / (lines[i + 1] - lines[i]), 0.0, 1.0)[:, None]
    return (1.0 - w) * table[i] + w * table[i + 1]


@dataclass
class VectorLUT:
    """A LUT given as vectors sampled along range at a set of azimuth lines.

    Each vector may have its own pixel sampling, so interpolation is done in
    two steps: along range per vector, then along azimuth between vectors.
    """

    lines: np.ndarray
    pixels: list[np.ndarray]
    values: list[np.ndarray]

    def interpolate(self, rows: np.ndarray, cols: np.ndarray) -> np.ndarray:
        rows = np.asarray(rows, dtype=np.float64)
        cols = np.asarray(cols, dtype=np.float64)
        per_vector = np.stack(
            [np.interp(cols, p, v) for p, v in zip(self.pixels, self.values, strict=True)]
        )
        return _interp_rows(rows, self.lines, per_vector)


@dataclass
class AzimuthNoiseBlock:
    """Azimuth noise scaling for one rectangular block (one sub-swath) of the image."""

    first_line: int
    last_line: int
    first_sample: int
    last_sample: int
    lines: np.ndarray
    lut: np.ndarray


@dataclass
class NoiseLUT:
    range_lut: VectorLUT
    azimuth_blocks: list[AzimuthNoiseBlock] = field(default_factory=list)

    def interpolate(self, rows: np.ndarray, cols: np.ndarray) -> np.ndarray:
        """Thermal noise power in DN^2 units on the ``rows`` x ``cols`` grid."""
        rows = np.asarray(rows, dtype=np.float64)
        cols = np.asarray(cols, dtype=np.float64)
        noise = self.range_lut.interpolate(rows, cols)
        if not self.azimuth_blocks:  # IPF < 2.9: range noise only
            return noise
        scale = np.ones_like(noise)
        for b in self.azimuth_blocks:
            r = (rows >= b.first_line) & (rows <= b.last_line)
            c = (cols >= b.first_sample) & (cols <= b.last_sample)
            if not r.any() or not c.any():
                continue
            az = np.interp(rows[r], b.lines, b.lut)
            scale[np.ix_(r, c)] = az[:, None]
        return noise * scale


def parse_calibration(xml: bytes | str, kind: str = "sigmaNought") -> VectorLUT:
    """Parse one calibration LUT (``sigmaNought``, ``betaNought``, ``gamma`` or ``dn``)."""
    root = ET.fromstring(xml)
    vecs = root.findall(".//calibrationVector")
    return VectorLUT(
        lines=np.array([float(v.findtext("line")) for v in vecs]),
        pixels=[_floats(v.findtext("pixel")) for v in vecs],
        values=[_floats(v.findtext(kind)) for v in vecs],
    )


def parse_noise(xml: bytes | str) -> NoiseLUT:
    root = ET.fromstring(xml)
    vecs = root.findall(".//noiseRangeVector")
    lut_tag = "noiseRangeLut"
    if not vecs:  # products processed with IPF < 2.9
        vecs = root.findall(".//noiseVector")
        lut_tag = "noiseLut"
    range_lut = VectorLUT(
        lines=np.array([float(v.findtext("line")) for v in vecs]),
        pixels=[_floats(v.findtext("pixel")) for v in vecs],
        values=[_floats(v.findtext(lut_tag)) for v in vecs],
    )
    blocks = []
    for v in root.findall(".//noiseAzimuthVector"):
        lines = _floats(v.findtext("line"))
        lut = _floats(v.findtext("noiseAzimuthLut"))
        if len(lines) == 1:  # a single value holds for the whole block
            lines, lut = np.repeat(lines, 2), np.repeat(lut, 2)
        blocks.append(
            AzimuthNoiseBlock(
                first_line=int(v.findtext("firstAzimuthLine")),
                last_line=int(v.findtext("lastAzimuthLine")),
                first_sample=int(v.findtext("firstRangeSample")),
                last_sample=int(v.findtext("lastRangeSample")),
                lines=lines,
                lut=lut,
            )
        )
    return NoiseLUT(range_lut, blocks)


class GeoGrid:
    """Image <-> geographic mapping from the annotation's geolocation grid.

    The forward model (line, pixel) -> (lat, lon) is a bicubic spline over the
    tie-point grid. The inverse is a piecewise-linear interpolator built on a
    dense sampling of the forward model, which is accurate to a small fraction
    of a pixel because the mapping is very smooth.
    """

    def __init__(self, lines, pixels, lat, lon, incidence, n_lines: int, n_samples: int):
        self.lines = np.asarray(lines, dtype=np.float64)
        self.pixels = np.asarray(pixels, dtype=np.float64)
        self.n_lines = n_lines
        self.n_samples = n_samples
        k_l = min(3, len(self.lines) - 1)
        k_p = min(3, len(self.pixels) - 1)
        self._lat = RectBivariateSpline(self.lines, self.pixels, lat, kx=k_l, ky=k_p)
        self._lon = RectBivariateSpline(self.lines, self.pixels, lon, kx=k_l, ky=k_p)
        self._inc = RectBivariateSpline(self.lines, self.pixels, incidence, kx=k_l, ky=k_p)
        self._inverse: LinearNDInterpolator | None = None

    @classmethod
    def from_points(cls, points: list[dict], n_lines: int, n_samples: int) -> GeoGrid:
        lines = np.unique([p["line"] for p in points])
        pixels = np.unique([p["pixel"] for p in points])
        index = {(p["line"], p["pixel"]): p for p in points}
        shape = (len(lines), len(pixels))
        lat, lon, inc = (np.empty(shape) for _ in range(3))
        for i, ln in enumerate(lines):
            for j, px in enumerate(pixels):
                p = index[(ln, px)]
                lat[i, j], lon[i, j], inc[i, j] = p["latitude"], p["longitude"], p["incidence"]
        return cls(lines, pixels, lat, lon, inc, n_lines, n_samples)

    def pixel_to_latlon(self, row, col) -> tuple[np.ndarray, np.ndarray]:
        row, col = np.asarray(row, dtype=np.float64), np.asarray(col, dtype=np.float64)
        return self._lat.ev(row, col), self._lon.ev(row, col)

    def incidence(self, row, col) -> np.ndarray:
        return self._inc.ev(np.asarray(row, np.float64), np.asarray(col, np.float64))

    def latlon_to_pixel(self, lat, lon) -> tuple[np.ndarray, np.ndarray]:
        """Inverse mapping; returns NaN for points outside the image footprint."""
        if self._inverse is None:
            r = np.linspace(0, self.n_lines - 1, 160)
            c = np.linspace(0, self.n_samples - 1, 160)
            rr, cc = np.meshgrid(r, c, indexing="ij")
            la, lo = self.pixel_to_latlon(rr.ravel(), cc.ravel())
            self._inverse = LinearNDInterpolator(
                np.column_stack([lo, la]), np.column_stack([rr.ravel(), cc.ravel()])
            )
        out = self._inverse(np.asarray(lon, np.float64), np.asarray(lat, np.float64))
        return out[..., 0], out[..., 1]

    def footprint(self, window=None, n: int = 20) -> np.ndarray:
        """Closed (lon, lat) ring tracing the border of ``window`` (row0, row1, col0, col1)."""
        r0, r1, c0, c1 = window or (0, self.n_lines - 1, 0, self.n_samples - 1)
        t = np.linspace(0, 1, n)
        rows = np.concatenate([r0 + 0 * t, r0 + (r1 - r0) * t, r1 + 0 * t, r1 - (r1 - r0) * t])
        cols = np.concatenate([c0 + (c1 - c0) * t, c1 + 0 * t, c1 - (c1 - c0) * t, c0 + 0 * t])
        lat, lon = self.pixel_to_latlon(rows, cols)
        return np.column_stack([lon, lat])


@dataclass
class ProductAnnotation:
    mission: str
    mode: str
    polarisation: str
    pass_direction: str
    start_time: str
    n_lines: int
    n_samples: int
    range_spacing: float
    azimuth_spacing: float
    geo: GeoGrid


def parse_product(xml: bytes | str) -> ProductAnnotation:
    root = ET.fromstring(xml)

    def text(path: str) -> str:
        value = root.findtext(path)
        if value is None:
            raise ValueError(f"annotation is missing {path}")
        return value

    n_lines = int(text(".//imageAnnotation/imageInformation/numberOfLines"))
    n_samples = int(text(".//imageAnnotation/imageInformation/numberOfSamples"))
    points = [
        {
            "line": int(p.findtext("line")),
            "pixel": int(p.findtext("pixel")),
            "latitude": float(p.findtext("latitude")),
            "longitude": float(p.findtext("longitude")),
            "incidence": float(p.findtext("incidenceAngle")),
        }
        for p in root.findall(".//geolocationGrid/geolocationGridPointList/geolocationGridPoint")
    ]
    return ProductAnnotation(
        mission=text(".//adsHeader/missionId"),
        mode=text(".//adsHeader/mode"),
        polarisation=text(".//adsHeader/polarisation"),
        pass_direction=text(".//generalAnnotation/productInformation/pass"),
        start_time=text(".//adsHeader/startTime"),
        n_lines=n_lines,
        n_samples=n_samples,
        range_spacing=float(text(".//imageAnnotation/imageInformation/rangePixelSpacing")),
        azimuth_spacing=float(text(".//imageAnnotation/imageInformation/azimuthPixelSpacing")),
        geo=GeoGrid.from_points(points, n_lines, n_samples),
    )
