/* 원자재·경제 거래 구조 데이터. 가격·재고 같은 변동값은 intel.js(cm)와 자동 수집(INTEL_AUTO.markets)에서 오고, 여기에는 바뀌지 않는 구조만 둔다. */
const COMMOD = {
  groups: [
    { id:"energy", n:"에너지", en:"ENERGY" }, { id:"metals", n:"금속", en:"METALS" }, { id:"ags", n:"농산물·소프트", en:"AGS & SOFTS" },
    { id:"inputs", n:"비료·운임", en:"INPUTS & FREIGHT" }, { id:"macro", n:"거시·환율·금리", en:"MACRO" }
  ],
  /* id, 이름, 그룹, 거래소·계약, 야후 티커(자동 시세), 단위, 핵심 동인, 한국 연관, 사건 태깅 정규식 */
  registry: [
    { id:"brent", n:"브렌트유", en:"Brent", g:"energy", ex:"ICE Brent", sym:"BZ=F", unit:"$/bbl", drivers:["호르무즈·홍해 통항","OPEC+ 산유 목표","비축유 방출","중국 수입·정제가동"], kr:"원유 도입가의 기준 벤치마크(두바이유와 연동)", rx:/브렌트|brent|두바이유|원유|유가|호르무즈|유조선|OPEC|산유|정유|비축유|crude|oil|tanker/i },
    { id:"wti", n:"WTI", en:"WTI", g:"energy", ex:"NYMEX CL", sym:"CL=F", unit:"$/bbl", drivers:["EIA 주간 재고·쿠싱","미 생산·수출","허리케인"], kr:"미국산 원유 도입 증가로 연관성 상승", rx:/WTI|쿠싱|EIA|셰일|미국산 원유/i },
    { id:"products", n:"석유제품(경유·휘발유)", en:"Refined products", g:"energy", ex:"NYMEX HO/RB", sym:"HO=F", unit:"$/gal", drivers:["정제 마진(크랙)","경유 재고","러시아 제품 수출 제한"], kr:"한국 정유 수출 마진 직결", rx:/경유|휘발유|디젤|항공유|정제|크랙|refin|diesel|gasoline/i },
    { id:"natgas", n:"천연가스(헨리허브)", en:"Henry Hub", g:"energy", ex:"NYMEX NG", sym:"NG=F", unit:"$/MMBtu", drivers:["미 생산·재고","LNG 수출 피드가스","기온"], kr:"미국산 LNG 장기계약 가격 연동", rx:/헨리허브|미국 가스|천연가스|natural gas/i },
    { id:"ttf", n:"유럽 가스(TTF)", en:"TTF", g:"energy", ex:"ICE Endex", sym:"TTF=F", unit:"€/MWh", drivers:["EU 저장률","노르웨이 정비","LNG 경쟁"], kr:"JKM과 경쟁해 현물 LNG 가격 결정", rx:/TTF|유럽 가스|EU 가스|저장률/i },
    { id:"jkm", n:"아시아 LNG(JKM)", en:"JKM", g:"energy", ex:"Platts JKM", sym:null, unit:"$/MMBtu", drivers:["카타르 불가항력","호르무즈 LNG 통항","동북아 기온"], kr:"한국 현물 LNG 도입가", rx:/JKM|LNG|카타르|라스라판|Qatar/i },
    { id:"coal", n:"유연탄(뉴캐슬)", en:"Newcastle coal", g:"energy", ex:"ICE Newcastle", sym:null, unit:"$/t", drivers:["중국·인도 수요","호주 공급","가스 대체"], kr:"발전 연료비·전기요금", rx:/유연탄|석탄|coal/i },
    { id:"uranium", n:"우라늄", en:"Uranium", g:"energy", ex:"Spot U3O8", sym:"URA", unit:"$/lb", drivers:["원전 재가동·신규","카자흐·니제르 공급","러시아 농축 제재"], kr:"원전 연료·원전 수출", rx:/우라늄|원전|핵연료|uranium/i },
    { id:"gold", n:"금", en:"Gold", g:"metals", ex:"COMEX GC", sym:"GC=F", unit:"$/oz", drivers:["실질금리·달러","중앙은행 매입","지정학 안전자산"], kr:"한국은행 외환보유·KRX 금시장", rx:/(^|[\s(])금([\s)]|$)|금값|금 현물|금 선물|골드|gold/i },
    { id:"silver", n:"은", en:"Silver", g:"metals", ex:"COMEX SI", sym:"SI=F", unit:"$/oz", drivers:["태양광 수요","금/은 비율"], kr:"", rx:/(^|[\s(])은([\s)]|$)|은값|은 현물|은 선물|silver/i },
    { id:"copper", n:"구리", en:"Copper", g:"metals", ex:"LME/COMEX HG", sym:"HG=F", unit:"$/lb", drivers:["중국 전력·건설","칠레·페루·콩고 공급","LME 재고·관세"], kr:"전선·배터리 소재 수입", rx:/구리|동값|copper|LME/i },
    { id:"aluminum", n:"알루미늄", en:"Aluminium", g:"metals", ex:"LME AH", sym:null, unit:"$/t", drivers:["중국 생산 상한","에너지 비용","관세"], kr:"", rx:/알루미늄|aluminum|aluminium/i },
    { id:"nickel", n:"니켈", en:"Nickel", g:"metals", ex:"LME NI", sym:null, unit:"$/t", drivers:["인도네시아 쿼터","배터리 수요"], kr:"배터리 양극재", rx:/니켈|nickel/i },
    { id:"ironore", n:"철광석", en:"Iron ore 62%", g:"metals", ex:"SGX/DCE", sym:null, unit:"$/t", drivers:["중국 조강 생산","호주·브라질 출하"], kr:"철강 원가", rx:/철광석|조강|iron ore|HRC|철강/i },
    { id:"lithium", n:"리튬·코발트", en:"Lithium / cobalt", g:"metals", ex:"탄산리튬 중국 현물", sym:"LIT", unit:"CNY/t", drivers:["EV 수요","콩고 코발트 수출 쿼터","칠레·호주 공급"], kr:"배터리 공급망", rx:/리튬|코발트|lithium|cobalt/i },
    { id:"rareearth", n:"희토류·전략광물", en:"Rare earths & critical", g:"metals", ex:"중국 현물(NdPr)", sym:null, unit:"CNY/t", drivers:["중국 수출통제 만료(11/10·11/27)","미국 비축·대체 공급"], kr:"반도체·방산 소재", rx:/희토류|갈륨|게르마늄|안티몬|텅스텐|rare earth|gallium/i },
    { id:"wheat", n:"밀", en:"Wheat", g:"ags", ex:"CBOT ZW", sym:"ZW=F", unit:"c/bu", drivers:["흑해 수출·공격","러시아 수출세","미 평원 가뭄"], kr:"제분·사료 수입", rx:/소맥|CBOT 밀|HRW 밀|제분밀|겨울밀|밀 (선물|가격|12월물|3월물|5월물|수출|수입|작황|생산|FOB|파종)|밀값|시카고 밀|캔자스 밀|MATIF|Euronext|흑해 곡물|wheat/i },
    { id:"corn", n:"옥수수", en:"Corn", g:"ags", ex:"CBOT ZC", sym:"ZC=F", unit:"c/bu", drivers:["미 수확·WASDE","에탄올","중국 수입"], kr:"사료 수입 1위 품목", rx:/옥수수|corn|maize/i },
    { id:"soy", n:"대두·대두유", en:"Soybeans", g:"ags", ex:"CBOT ZS", sym:"ZS=F", unit:"c/bu", drivers:["브라질 파종·기상","미중 구매 합의","바이오디젤"], kr:"식용유·사료", rx:/대두|콩|soy/i },
    { id:"rice", n:"쌀", en:"Rice", g:"ags", ex:"CBOT ZR / 태국 FOB", sym:"ZR=F", unit:"$/cwt", drivers:["인도 수출 정책","몬순"], kr:"", rx:/(^|[\s(])쌀([\s)]|$)|쌀값|쇄미|백미|인디카|rice/i },
    { id:"palm", n:"팜유·식물성유", en:"Palm oil", g:"ags", ex:"BMD FCPO", sym:null, unit:"MYR/t", drivers:["말레이 재고","인니 바이오디젤","대두유 스프레드"], kr:"", rx:/팜유|식물성유|palm/i },
    { id:"sugar", n:"설탕", en:"Sugar No.11", g:"ags", ex:"ICE SB", sym:"SB=F", unit:"c/lb", drivers:["브라질 수확·에탄올 배분","인도 수출"], kr:"", rx:/설탕|sugar/i },
    { id:"coffee", n:"커피", en:"Coffee", g:"ags", ex:"ICE KC", sym:"KC=F", unit:"c/lb", drivers:["브라질 서리·강우","베트남 로부스타"], kr:"", rx:/커피|아라비카|로부스타|coffee|arabica|robusta/i },
    { id:"cocoa", n:"코코아", en:"Cocoa", g:"ags", ex:"ICE CC", sym:"CC=F", unit:"$/t", drivers:["코트디부아르·가나 작황","재고"], kr:"", rx:/코코아|cocoa/i },
    { id:"cotton", n:"면화", en:"Cotton", g:"ags", ex:"ICE CT", sym:"CT=F", unit:"c/lb", drivers:["미 텍사스 작황","중국 수요"], kr:"", rx:/면화|cotton/i },
    { id:"fert", n:"비료(요소·DAP·칼륨)", en:"Fertilizer", g:"inputs", ex:"NOLA/중동 FOB", sym:null, unit:"$/t", drivers:["가스 가격","중국·러시아 수출 제한","걸프 요소 수출"], kr:"농가 원가", rx:/비료|요소|칼륨|인산|fertilizer|urea|potash/i },
    { id:"bdi", n:"건화물 운임(BDI)", en:"Baltic Dry", g:"inputs", ex:"Baltic Exchange", sym:null, unit:"지수", drivers:["철광석·곡물 물동량","선복 공급"], kr:"벌크 수입 운임", rx:/BDI|건화물|케이프|파나막스|Baltic|dry bulk/i },
    { id:"container", n:"컨테이너 운임(WCI·SCFI)", en:"Container rates", g:"inputs", ex:"Drewry/SSE", sym:null, unit:"$/FEU", drivers:["홍해 우회","선복 과잉","미 관세 선적"], kr:"수출 물류비", rx:/컨테이너|WCI|SCFI|FBX|FEU|TEU|선사|Maersk|머스크|하파그|MSC/i },
    { id:"tanker", n:"유조선 운임(VLCC)", en:"Tanker rates", g:"inputs", ex:"TD3C", sym:null, unit:"$/day", drivers:["호르무즈 우회 톤마일","제재 선박"], kr:"원유 수입 운임", rx:/VLCC|유조선 운임|탱커|tanker rate/i },
    { id:"usd", n:"달러인덱스·원/달러", en:"DXY / USDKRW", g:"macro", ex:"ICE DXY", sym:"DX-Y.NYB", unit:"지수", drivers:["연준 경로","안전자산","무역수지"], kr:"수입 물가·환헤지", rx:/달러|환율|원화|DXY|dollar/i },
    { id:"rates", n:"미 국채 10년물", en:"US 10y", g:"macro", ex:"CBOT ZN", sym:"^TNX", unit:"%", drivers:["물가·연준","재정 적자 발행"], kr:"국고채·주담대 금리", rx:/국채|10년물|기준금리|연준|FOMC|yield|Treasury|TIPS/i },
    { id:"vix", n:"변동성(VIX)", en:"VIX", g:"macro", ex:"CBOE", sym:"^VIX", unit:"지수", drivers:["위험선호","이벤트"], kr:"", rx:/VIX|변동성|volatility/i },
    { id:"kospi", n:"코스피·반도체", en:"KOSPI", g:"macro", ex:"KRX", sym:"^KS11", unit:"지수", drivers:["반도체 사이클","외국인 수급","환율"], kr:"국내 자산", rx:/코스피|KOSPI|반도체|삼성전자|SK하이닉스/i },
    { id:"btc", n:"비트코인", en:"Bitcoin", g:"macro", ex:"Spot", sym:"BTC-USD", unit:"$", drivers:["ETF 자금","달러 유동성"], kr:"", rx:/비트코인|bitcoin|BTC/i }
  ],
  /* 지구본 자원 거점. k: oil|lng|gas|mine|grain|refine|port */
  hubs: [
    { n:"라스타누라", en:"Ras Tanura", at:[50.15,26.64], k:"oil", c:"사우디", cm:["brent"], x:"세계 최대 원유 수출 터미널" },
    { n:"카르그섬", en:"Kharg Island", at:[50.32,29.23], k:"oil", c:"이란", cm:["brent"], x:"이란 원유 수출 90%" },
    { n:"푸자이라", en:"Fujairah", at:[56.33,25.12], k:"oil", c:"UAE", cm:["brent","products"], x:"호르무즈 밖 수출·벙커링 허브" },
    { n:"얀부", en:"Yanbu", at:[38.06,24.09], k:"oil", c:"사우디", cm:["brent"], x:"동서 파이프라인 종점" },
    { n:"바스라 터미널", en:"Basra Oil Terminal", at:[48.8,29.68], k:"oil", c:"이라크", cm:["brent"], x:"이라크 수출 85%" },
    { n:"라스라판", en:"Ras Laffan", at:[51.55,25.9], k:"lng", c:"카타르", cm:["jkm","ttf"], x:"세계 최대 LNG 수출 단지, 불가항력" },
    { n:"사빈패스", en:"Sabine Pass", at:[-93.87,29.73], k:"lng", c:"미국", cm:["natgas","jkm"], x:"미 최대 LNG 수출" },
    { n:"글래드스톤·커티스섬", en:"Gladstone LNG", at:[151.25,-23.85], k:"lng", c:"호주", cm:["jkm"], x:"동호주 LNG" },
    { n:"야말 LNG", en:"Yamal LNG", at:[72.07,71.26], k:"lng", c:"러시아", cm:["ttf","jkm"], x:"북극 LNG" },
    { n:"프리모르스크", en:"Primorsk", at:[28.73,60.35], k:"oil", c:"러시아", cm:["brent"], x:"발트해 원유 수출" },
    { n:"노보로시스크", en:"Novorossiysk", at:[37.77,44.72], k:"port", c:"러시아", cm:["brent","wheat"], x:"흑해 원유·곡물 수출" },
    { n:"오데사", en:"Odesa", at:[30.73,46.48], k:"grain", c:"우크라이나", cm:["wheat","corn","soy"], x:"흑해 곡물 회랑" },
    { n:"쿠싱", en:"Cushing", at:[-96.77,35.98], k:"oil", c:"미국", cm:["wti"], x:"WTI 인도 지점·저장 허브" },
    { n:"휴스턴 정제벨트", en:"Houston refining", at:[-95.0,29.7], k:"refine", c:"미국", cm:["products","wti"], x:"걸프 정제능력 집중" },
    { n:"로테르담", en:"Rotterdam", at:[4.47,51.92], k:"refine", c:"네덜란드", cm:["products","ttf"], x:"ARA 제품 허브" },
    { n:"싱가포르", en:"Singapore", at:[103.8,1.3], k:"refine", c:"싱가포르", cm:["products","brent"], x:"아시아 제품 벤치마크" },
    { n:"울산", en:"Ulsan", at:[129.36,35.5], k:"refine", c:"한국", cm:["products","brent"], x:"SK·S-Oil 정제·수출" },
    { n:"에스콘디다", en:"Escondida", at:[-69.07,-24.27], k:"mine", c:"칠레", cm:["copper"], x:"세계 최대 구리 광산" },
    { n:"그래스버그", en:"Grasberg", at:[137.12,-4.06], k:"mine", c:"인도네시아", cm:["copper","gold"], x:"구리·금, 2025 사고 후 복구" },
    { n:"카탕가 코발트벨트", en:"Katanga", at:[27.5,-11.0], k:"mine", c:"콩고", cm:["lithium","copper"], x:"세계 코발트 70%" },
    { n:"바이윈어보", en:"Bayan Obo", at:[109.97,41.77], k:"mine", c:"중국", cm:["rareearth"], x:"희토류 최대 광산" },
    { n:"술라웨시 니켈벨트", en:"Sulawesi nickel", at:[122.3,-2.7], k:"mine", c:"인도네시아", cm:["nickel"], x:"세계 니켈 50%+" },
    { n:"필바라·포트헤들랜드", en:"Port Hedland", at:[118.6,-20.31], k:"port", c:"호주", cm:["ironore"], x:"세계 최대 철광석 수출항" },
    { n:"카라자스", en:"Carajás", at:[-50.17,-6.07], k:"mine", c:"브라질", cm:["ironore"], x:"발레 철광석" },
    { n:"아타카마 리튬", en:"Atacama lithium", at:[-68.3,-23.5], k:"mine", c:"칠레", cm:["lithium"], x:"염수 리튬" },
    { n:"그린부시", en:"Greenbushes", at:[116.06,-33.86], k:"mine", c:"호주", cm:["lithium"], x:"경암 리튬 최대" },
    { n:"뉴캐슬", en:"Newcastle", at:[151.78,-32.93], k:"port", c:"호주", cm:["coal"], x:"발전탄 벤치마크 항" },
    { n:"카자흐 우라늄", en:"Kazakhstan uranium", at:[67.0,44.5], k:"mine", c:"카자흐스탄", cm:["uranium"], x:"세계 우라늄 40%" },
    { n:"산투스", en:"Santos", at:[-46.33,-23.96], k:"grain", c:"브라질", cm:["soy","corn","sugar","coffee"], x:"대두·설탕·커피 수출항" },
    { n:"로사리오", en:"Rosario", at:[-60.64,-32.95], k:"grain", c:"아르헨티나", cm:["soy","corn","wheat"], x:"파라나강 곡물 허브" },
    { n:"뉴올리언스 걸프", en:"US Gulf (NOLA)", at:[-90.07,29.95], k:"grain", c:"미국", cm:["corn","soy","fert"], x:"미 곡물 수출 60%·비료 기준가" },
    { n:"아비장", en:"Abidjan", at:[-4.02,5.35], k:"port", c:"코트디부아르", cm:["cocoa"], x:"코코아 수출 1위" },
    { n:"말레이 팜유벨트", en:"Malaysia palm", at:[102.0,3.5], k:"grain", c:"말레이시아", cm:["palm"], x:"BMD 팜유" },
    { n:"파나마 운하", en:"Panama Canal", at:[-79.7,9.1], k:"port", c:"파나마", cm:["natgas","corn","container"], x:"LNG·곡물 통항, 엘니뇨 수위" },
    { n:"수에즈 운하", en:"Suez Canal", at:[32.45,30.4], k:"port", c:"이집트", cm:["container","brent","products"], x:"아시아–유럽 본선" },
    { n:"파나막스 벌크·케이프 항로", en:"Cape route", at:[18.4,-34.6], k:"port", c:"남아공", cm:["container","bdi"], x:"우회 톤마일" },
    { n:"상하이항", en:"Shanghai", at:[121.5,31.2], k:"port", c:"중국", cm:["container"], x:"SCFI 기준항" },
    { n:"부산항", en:"Busan", at:[129.08,35.1], k:"port", c:"한국", cm:["container"], x:"환적 허브" },
    { n:"젯다·킹압둘라항", en:"Jeddah", at:[39.17,21.5], k:"port", c:"사우디", cm:["container","fert"], x:"홍해 컨테이너·비료" },
    { n:"댐맘·주베일", en:"Jubail", at:[49.65,27.0], k:"refine", c:"사우디", cm:["fert","products"], x:"SABIC 요소·석유화학" },
    { n:"이집트 다미에타 LNG", en:"Damietta LNG", at:[31.8,31.42], k:"lng", c:"이집트", cm:["ttf"], x:"동지중해 LNG" }
  ],
  /* 분쟁·사건 → 상품 전파. dir: + 상승압력, - 하락압력. lag: 즉시|수일|수주 */
  transmission: [
    { th:"iran", cm:"brent", dir:"+", w:3, lag:"즉시", m:"호르무즈 통항·유조선 피격 → 공급 리스크 프리미엄" },
    { th:"iran", cm:"jkm", dir:"+", w:3, lag:"즉시", m:"카타르 LNG 통항 제약·불가항력" },
    { th:"iran", cm:"tanker", dir:"+", w:3, lag:"즉시", m:"우회 톤마일·전쟁보험료" },
    { th:"iran", cm:"fert", dir:"+", w:2, lag:"수일", m:"걸프 요소 수출 차질·가스가 상승" },
    { th:"iran", cm:"gold", dir:"+", w:2, lag:"즉시", m:"안전자산 수요" },
    { th:"yemen", cm:"container", dir:"+", w:3, lag:"수일", m:"홍해 재우회·수에즈 통항 감소" },
    { th:"yemen", cm:"brent", dir:"+", w:1, lag:"수일", m:"얀부 수출 차질 시" },
    { th:"ukraine", cm:"wheat", dir:"+", w:3, lag:"즉시", m:"오데사 항만 피격·흑해 수출 역량" },
    { th:"ukraine", cm:"corn", dir:"+", w:2, lag:"수일", m:"흑해 옥수수 수출" },
    { th:"ukraine", cm:"products", dir:"+", w:2, lag:"수일", m:"러시아 정유시설 드론 → 경유 수출 감소" },
    { th:"ukraine", cm:"ttf", dir:"+", w:1, lag:"수주", m:"러 가스 인프라·TurkStream" },
    { th:"ukraine", cm:"fert", dir:"+", w:2, lag:"수주", m:"러·벨라루스 칼륨·요소 공급" },
    { th:"taiwan", cm:"container", dir:"+", w:2, lag:"즉시", m:"대만해협·루손 항로 리스크" },
    { th:"taiwan", cm:"kospi", dir:"-", w:2, lag:"즉시", m:"반도체 공급망 리스크 프리미엄" },
    { th:"taiwan", cm:"rareearth", dir:"+", w:2, lag:"수주", m:"미중 통제 보복 연동" },
    { th:"drc", cm:"lithium", dir:"+", w:2, lag:"수주", m:"코발트 수출·동부 분쟁" },
    { th:"drc", cm:"copper", dir:"+", w:1, lag:"수주", m:"카탕가 물류" },
    { th:"sahel", cm:"uranium", dir:"+", w:1, lag:"수주", m:"니제르 우라늄" },
    { th:"sahel", cm:"gold", dir:"+", w:1, lag:"수주", m:"말리·부르키나 금 생산" },
    { th:"somalia", cm:"tanker", dir:"+", w:1, lag:"수일", m:"아덴만 해적 보험료" },
    { th:"carib", cm:"brent", dir:"-", w:1, lag:"수주", m:"베네수엘라 수출 재개 시 공급 증가" },
    { th:"korea", cm:"kospi", dir:"-", w:2, lag:"즉시", m:"지정학 리스크 프리미엄" },
    { th:"korea", cm:"usd", dir:"+", w:1, lag:"즉시", m:"원화 약세 압력" },
    { th:"ethiopia", cm:"coffee", dir:"+", w:1, lag:"수주", m:"에티오피아 아라비카 수출" },
    { th:"sudan", cm:"gold", dir:"0", w:1, lag:"수주", m:"수단 금 밀수·수출 경로" },
    { th:"gaza", cm:"brent", dir:"+", w:1, lag:"즉시", m:"확전 시 역내 프리미엄" },
    { th:"myanmar", cm:"rareearth", dir:"+", w:1, lag:"수주", m:"카친 희토류 광산" },
    { th:"afpak", cm:"rareearth", dir:"0", w:1, lag:"수주", m:"아프간 광물 개발 기대" },
    { th:"latam", cm:"copper", dir:"+", w:2, lag:"수주", m:"에스콘디다·센티넬라 파업 → 세계 공급 6% 차질" },
    { th:"latam", cm:"soy", dir:"-", w:1, lag:"수개월", m:"브라질 결선·헤알화 → 수출 물량" },
    { th:"latam", cm:"lithium", dir:"-", w:1, lag:"수개월", m:"아르헨티나 증산·인도 확보 → 공급 과잉" },
    { th:"namerica", cm:"aluminum", dir:"+", w:2, lag:"즉시", m:"캐나다 관세 → 미국 내 알루미늄 프리미엄" },
    { th:"namerica", cm:"silver", dir:"+", w:1, lag:"수주", m:"멕시코 타격·보복 → 세계 1위 은 생산국 리스크" },
    { th:"oceania", cm:"ironore", dir:"-", w:2, lag:"수주", m:"CMRG 가격 압박·구매 중단 → 벤치마크 하락" },
    { th:"oceania", cm:"jkm", dir:"+", w:1, lag:"수주", m:"호주 LNG 차질·가격 상향 전망" },
    { th:"europe", cm:"brent", dir:"+", w:2, lag:"즉시", m:"발트해 나포·NSR 사고 → 러시아 수출 차질" },
    { th:"europe", cm:"tanker", dir:"+", w:1, lag:"즉시", m:"그림자함대 검문 → 보험료·운임" },
    { th:"southasia", cm:"rice", dir:"+", w:1, lag:"수주", m:"인도 수출 통제·분쟁 → 아시아 쌀" }
  ],
  calendarCats: { macro:"거시", energy:"에너지", ags:"농산물", metals:"금속", policy:"정책", geo:"지정학" }
};
