/* 시나리오 충격 모델(5차). 각 시나리오는 전역(th)·기본 확률(p, %)·지평(h, 일)과 상품별 조건부 충격(m: 평균 %, s: 표준편차 %)을 가진다.
   같은 전역의 시나리오는 상호배타적으로 추출한다. 금리(rates)는 bp, VIX는 지수 변화율(%). 분석관이 확률·강도를 조정해 몬테카를로로 분포를 본다. */
const SCEN = {
  asof: "2026-10-08",
  /* 연율 변동성(%)과 백테스트 시리즈 심볼. 몬테카를로의 기저 잡음에 쓴다. */
  assets: {
    brent:{vol:38, sym:"BZ=F"}, wti:{vol:40, sym:"CL=F"}, products:{vol:42, sym:"HO=F"}, natgas:{vol:60, sym:"NG=F"}, ttf:{vol:70, sym:"TTF=F"}, jkm:{vol:55}, coal:{vol:35}, uranium:{vol:30, sym:"URA"},
    gold:{vol:16, sym:"GC=F"}, silver:{vol:30, sym:"SI=F"}, copper:{vol:26, sym:"HG=F"}, aluminum:{vol:22}, nickel:{vol:35}, ironore:{vol:30}, lithium:{vol:45, sym:"LIT"}, rareearth:{vol:40},
    wheat:{vol:30, sym:"ZW=F"}, corn:{vol:25, sym:"ZC=F"}, soy:{vol:22, sym:"ZS=F"}, rice:{vol:20, sym:"ZR=F"}, palm:{vol:28}, sugar:{vol:32, sym:"SB=F"}, coffee:{vol:38, sym:"KC=F"}, cocoa:{vol:50, sym:"CC=F"}, cotton:{vol:25, sym:"CT=F"}, fert:{vol:35},
    bdi:{vol:60, sym:"BDRY"}, container:{vol:45}, tanker:{vol:90}, usd:{vol:7, sym:"DX-Y.NYB"}, rates:{vol:0, bp:true, sym:"^TNX"}, vix:{vol:110, sym:"^VIX"}, kospi:{vol:22, sym:"^KS11"}, btc:{vol:60, sym:"BTC-USD"}
  },
  templates: [
    { id:"hormuz_persist", th:"iran", n:"통제된 해협 지속", en:"Hormuz: controlled passage persists", p:60, h:30,
      d:"선별 통항·간헐 공격·봉쇄 병존. 유가 95~110달러 박스권, 보험료 고공.",
      shocks:{brent:{m:3,s:7}, wti:{m:2,s:7}, products:{m:4,s:8}, jkm:{m:4,s:9}, ttf:{m:3,s:9}, tanker:{m:10,s:25}, fert:{m:6,s:8}, gold:{m:1,s:2}, kospi:{m:-1,s:3}},
      korea:"원유 도입 단가 고정 부담, 현물 LNG 프리미엄 유지. 정유 마진은 양호.", tripwires:["hormuz_transits_low","brent_110"], analogs:["hormuz_closure_2026","hormuz_reopening_rejected_2026","abqaiq_drone_attack_2019","iraq_invades_kuwait_1990"],
      watch:["PortWatch 호르무즈 일 통항 20척 하회 지속","카타르 중재 접촉 중단","VLCC 전쟁위험 보험료 7% 상회"] },
    { id:"hormuz_reopen", th:"iran", n:"중재 타결·단계적 재개방", en:"Hormuz: mediated reopening", p:30, h:30,
      d:"카타르·오만 중재로 7~14일 내 통항 복원. 공급 프리미엄 급락.",
      shocks:{brent:{m:-18,s:6}, wti:{m:-15,s:6}, products:{m:-14,s:6}, jkm:{m:-22,s:8}, ttf:{m:-15,s:7}, natgas:{m:-3,s:4}, tanker:{m:-45,s:15}, fert:{m:-15,s:7}, gold:{m:-3,s:2}, usd:{m:-1.5,s:1}, vix:{m:-20,s:10}, kospi:{m:4,s:3}, container:{m:-3,s:4}},
      korea:"도입가 급락은 2개월 시차로 반영. 조기 장기계약 체결 유인.", tripwires:["brent_85"], analogs:["desert_storm_start_1991","iran_strikes_israel_2024"],
      watch:["이란 외무부 '통항 보장' 성명","호르무즈 통항 30척/일 회복","브렌트-두바이 EFS 5달러 하회"] },
    { id:"hormuz_war", th:"iran", n:"전면 확전·장기 봉쇄", en:"Hormuz: full escalation, prolonged closure", p:10, h:60,
      d:"미·이란 직접 교전, 걸프 생산시설 타격, 30일 이상 사실상 폐쇄.",
      shocks:{brent:{m:45,s:15}, wti:{m:35,s:13}, products:{m:40,s:14}, jkm:{m:50,s:18}, ttf:{m:35,s:14}, natgas:{m:8,s:6}, coal:{m:10,s:6}, tanker:{m:120,s:50}, container:{m:12,s:8}, fert:{m:30,s:12}, gold:{m:8,s:4}, usd:{m:3,s:1.5}, rates:{m:-25,s:15}, vix:{m:80,s:35}, kospi:{m:-10,s:4}, btc:{m:-8,s:8}, aluminum:{m:6,s:4}},
      korea:"비축유 방출·수요 억제 단계. 석유화학 가동 축소, 물가 1%p 상방.", tripwires:["hormuz_transits_low","brent_110","vix_30","krw_1400"], analogs:["hormuz_closure_2026","iraq_invades_kuwait_1990","russia_invades_ukraine_2022"],
      watch:["걸프 정유·LNG 시설 피격","미 항모 3척 중부사령부 집결","카타르 LNG 불가항력 확대"] },
    { id:"redsea_houthi", th:"yemen", n:"후티 해상 반격 재개", en:"Red Sea: Houthi maritime offensive resumes", p:25, h:30,
      d:"바브엘만데브 상선 공격 재개, 수에즈 복귀 선사 재이탈.",
      shocks:{container:{m:35,s:12}, tanker:{m:15,s:10}, brent:{m:5,s:4}, bdi:{m:5,s:6}, products:{m:4,s:4}, kospi:{m:-1,s:2}},
      korea:"유럽향 수출 운임 급등, 납기 10~14일 지연.", tripwires:["bab_transits_low","maritime_attacks"], analogs:["houthi_galaxy_leader_2023","ever_given_suez_2021"],
      watch:["UKMTO 경보 24시간 2건 이상","머스크·하파그 희망봉 재우회 공지","바브엘만데브 일 통항 20척 미만"] },
    { id:"redsea_calm", th:"yemen", n:"연합 조기 승리·수에즈 완전 복귀", en:"Red Sea: coalition victory, full Suez return", p:30, h:60,
      d:"후티 해안 거점 상실, 전쟁위험 할증 소멸, 선복 과잉 노출.",
      shocks:{container:{m:-20,s:8}, tanker:{m:-8,s:6}, bdi:{m:-3,s:5}, brent:{m:-2,s:3}},
      korea:"해운사 수익 압박, 수출기업 물류비 절감.", tripwires:[], analogs:["ever_given_suez_2021"],
      watch:["아시아-북유럽 수에즈 복귀율 30% 상회","전쟁위험 할증 폐지 공지"] },
    { id:"blacksea_escalate", th:"ukraine", n:"흑해 해상 확전", en:"Black Sea: maritime escalation", p:15, h:30,
      d:"오데사 3항·노보로시스크 동시 타격, 곡물 회랑 사실상 중단.",
      shocks:{wheat:{m:25,s:10}, corn:{m:12,s:6}, soy:{m:4,s:3}, palm:{m:4,s:3}, fert:{m:15,s:7}, brent:{m:4,s:4}, ttf:{m:12,s:8}, gold:{m:2,s:2}, vix:{m:15,s:10}},
      korea:"제분·사료 원가 급등, 밀 수입선 호주·미국 전환.", tripwires:["wheat_800","ttf_100"], analogs:["novorossiysk_grain_terminals_attack_2026","russia_invades_ukraine_2022","black_sea_grain_initiative_collapse_2023","russia_wheat_export_ban_2010"],
      watch:["우크라이나 월 곡물 수출 100만t 하회","러 터미널 추가 피격","흑해 전쟁위험 보험 인수 중단"] },
    { id:"blacksea_deal", th:"ukraine", n:"부분 합의·터미널 복구", en:"Black Sea: partial deal, terminals restored", p:30, h:60,
      d:"3자 회담 후 해상 휴전, 러시아 터미널 80% 재가동.",
      shocks:{wheat:{m:-15,s:6}, corn:{m:-7,s:4}, fert:{m:-8,s:5}, ttf:{m:-8,s:6}, brent:{m:-3,s:3}, vix:{m:-8,s:6}},
      korea:"곡물 도입가 안정, 비료 가격 완화.", tripwires:[], analogs:["black_sea_grain_initiative_signed_2022"],
      watch:["해상 휴전 문안 합의","노보로시스크 선적 재개 보도","SRW 펀드 순숏 커버"] },
    { id:"taiwan_quarantine", th:"taiwan", n:"대만 격리·봉쇄", en:"Taiwan: quarantine or blockade", p:5, h:60,
      d:"중국 해경 주도 '검역' 선언, 대만해협·바시해협 통항 통제.",
      shocks:{kospi:{m:-15,s:6}, vix:{m:70,s:30}, usd:{m:3,s:1.5}, gold:{m:6,s:3}, rates:{m:-30,s:15}, copper:{m:-8,s:5}, ironore:{m:-6,s:4}, aluminum:{m:-4,s:3}, container:{m:25,s:12}, rareearth:{m:40,s:20}, lithium:{m:10,s:8}, btc:{m:-15,s:10}, brent:{m:3,s:5}, jkm:{m:10,s:8}},
      korea:"반도체 공급망 타격, 원화 급락, 외국인 자금 이탈. 대만해협 우회로 운임 급등.", tripwires:["pla_air_40","vix_30","krw_1400"], analogs:["crimea_annexation_2014","covid_opec_price_war_2020"],
      watch:["PLA 항공기 일 40대 이상 연속","중국 해경 '검역' 용어 사용","미 항모 서태평양 공백 지속"] },
    { id:"korea_strategic", th:"korea", n:"북한 전략 도발(핵실험·ICBM)", en:"North Korea: strategic provocation", p:10, h:20,
      d:"7차 핵실험 또는 정상각 ICBM. 한미 확장억제 강화 조치.",
      shocks:{kospi:{m:-4,s:3}, usd:{m:0.5,s:0.5}, vix:{m:12,s:8}, gold:{m:1.5,s:1.5}},
      korea:"원화 1~2% 약세, 외국인 단기 매도. 과거 사례상 5일 내 복원.", tripwires:["korea_missile"], analogs:["sept11_attacks_2001"],
      watch:["풍계리 3번 갱도 차량 증가","당 창건일(10/10) 전후 발사 징후"] },
    { id:"us_china_tariff", th:"taiwan", n:"미·중 관세·희토류 통제 재격화", en:"US-China: tariff and rare-earth escalation", p:25, h:60,
      d:"휴전 연장 파기, 희토류·배터리 소재 수출통제 확대, 미 관세 복원.",
      shocks:{rareearth:{m:50,s:25}, lithium:{m:8,s:6}, soy:{m:-8,s:4}, copper:{m:-5,s:4}, kospi:{m:-6,s:3}, usd:{m:1.5,s:1}, vix:{m:30,s:15}, btc:{m:-8,s:8}, container:{m:-10,s:8}, gold:{m:3,s:2}},
      korea:"희토류·흑연 수급 차질, 대중 중간재 수출 둔화.", tripwires:["dxy_105"], analogs:["liberation_day_tariffs_2025"],
      watch:["중국 상무부 수출통제 공고","미 301조 복원 발표","중국 미국산 대두 구매 중단"] },
    { id:"us_recession", th:"macro", n:"미 경기 급랭·연준 긴급 인하", en:"US hard landing, emergency Fed cuts", p:15, h:60,
      d:"고용 급감·신용 경색. 위험자산 디레버리징.",
      shocks:{brent:{m:-20,s:8}, wti:{m:-22,s:8}, copper:{m:-15,s:6}, ironore:{m:-12,s:6}, rates:{m:-80,s:30}, vix:{m:60,s:30}, usd:{m:-2,s:2}, gold:{m:8,s:4}, kospi:{m:-12,s:5}, bdi:{m:-25,s:10}, btc:{m:-20,s:12}, nickel:{m:-10,s:6}, aluminum:{m:-8,s:5}},
      korea:"수출 급감, 반도체 재고 사이클 재진입. 국고채 강세.", tripwires:["vix_30"], analogs:["lehman_collapse_2008","covid_opec_price_war_2020","yen_carry_unwind_2024"],
      watch:["미 실업률 3개월 0.5%p 상승(삼 룰)","하이일드 스프레드 500bp"] },
    { id:"fed_hawkish", th:"macro", n:"연준 추가 인상·10년물 5.5%", en:"Fed hikes again, 10y to 5.5%", p:25, h:60,
      d:"물가 재가속으로 인상 재개. 달러 강세·금리 민감 자산 약세.",
      shocks:{rates:{m:40,s:15}, usd:{m:2.5,s:1}, gold:{m:-6,s:3}, silver:{m:-9,s:4}, kospi:{m:-7,s:3}, vix:{m:25,s:12}, copper:{m:-5,s:3}, btc:{m:-12,s:8}, brent:{m:-4,s:3}},
      korea:"원화 약세, 가계 이자 부담, 외국인 채권 자금 이탈.", tripwires:["us10y_55","dxy_105","krw_1400"], analogs:["yen_carry_unwind_2024"],
      watch:["미 CPI 전월비 0.4% 이상 2개월 연속","FOMC 점도표 상향"] },
    { id:"china_stimulus", th:"macro", n:"중국 대규모 재정 부양", en:"China: large fiscal stimulus", p:20, h:60,
      d:"인프라·부동산 완충 패키지. 산업금속·건화물 수요 기대.",
      shocks:{copper:{m:8,s:4}, ironore:{m:12,s:6}, aluminum:{m:5,s:3}, nickel:{m:6,s:4}, bdi:{m:15,s:10}, coal:{m:5,s:4}, kospi:{m:4,s:2}, usd:{m:-1,s:1}},
      korea:"철강·화학 수출 반등, 대중 중간재 수요 회복.", tripwires:[], analogs:[],
      watch:["전인대 상무위 특별국채 승인","신규 대출 급증"] },
    { id:"elnino_super", th:"weather", n:"역대급 엘니뇨 확정", en:"Record El Niño confirmed", p:70, h:90,
      d:"1950년 이후 최강. 동남아·인도·호주 동부·서아프리카 건조, 남미 남부 다우.",
      shocks:{palm:{m:15,s:8}, sugar:{m:12,s:7}, coffee:{m:10,s:8}, cocoa:{m:10,s:10}, rice:{m:15,s:8}, wheat:{m:5,s:4}, corn:{m:-2,s:3}, soy:{m:2,s:3}, natgas:{m:-6,s:5}, bdi:{m:-4,s:5}, container:{m:4,s:4}, cotton:{m:4,s:4}},
      korea:"식용유·설탕·커피 수입가 상승, 겨울 난방 수요 감소.", tripwires:[], analogs:[],
      watch:["NOAA ONI 2.0 이상","인도 쌀 수출 제한 재도입","파나마 흘수 재제한"] },
    { id:"gulf_hurricane", th:"weather", n:"멕시코만 허리케인 상륙", en:"Gulf of Mexico hurricane landfall", p:35, h:10,
      d:"정유 6곳·LNG·NOLA 비료 터미널 일시 가동 중단.",
      shocks:{products:{m:6,s:3}, natgas:{m:5,s:4}, fert:{m:4,s:3}, brent:{m:2,s:2}, corn:{m:1,s:1}, soy:{m:1,s:1}},
      korea:"미국산 LNG 스팟 카고 지연, 경유 수출 마진 개선.", tripwires:[], analogs:[],
      watch:["걸프 정유 가동 중단 용량 100만 b/d 이상","NOLA 요소 바지선 운항 중단"] },
    { id:"opec_hike", th:"macro", n:"OPEC+ 증산 가속", en:"OPEC+ accelerates output hikes", p:20, h:60,
      d:"호르무즈 재개방과 맞물린 점유율 경쟁. 과잉 공급 전환.",
      shocks:{brent:{m:-10,s:5}, wti:{m:-10,s:5}, products:{m:-8,s:4}, tanker:{m:10,s:10}, natgas:{m:-2,s:3}},
      korea:"도입가 하락, 정유 재고평가 손실.", tripwires:["brent_85"], analogs:["covid_opec_price_war_2020"],
      watch:["OPEC+ 월간 회의 증산 폭 40만 b/d 이상","사우디 OSP 인하"] },
    { id:"ethiopia_war", th:"ethiopia", n:"에티오피아–에리트레아 국가 간 전쟁", en:"Ethiopia–Eritrea interstate war", p:50, h:60,
      d:"아세브 항구 공세, 홍해 남부 추가 불안.",
      shocks:{coffee:{m:4,s:3}, container:{m:5,s:4}, tanker:{m:3,s:3}, gold:{m:1,s:1}},
      korea:"에티오피아 아라비카 수입 차질, 홍해 남부 운임 추가 할증.", tripwires:["ethiopia_interstate"], analogs:[],
      watch:["아세브 방면 기갑 이동","에리트레아 총동원령"] },
    { id:"venezuela_land", th:"carib", n:"베네수엘라 육상 작전 확대", en:"Venezuela: land operations expand", p:10, h:30,
      d:"미군 지상 개입, 오리노코 생산 차질.",
      shocks:{brent:{m:4,s:3}, wti:{m:5,s:3}, products:{m:3,s:3}, gold:{m:1,s:1}},
      korea:"중질유 수급 영향 제한적.", tripwires:[], analogs:["libya_uprising_2011"],
      watch:["미 남부사령부 상륙부대 전개","PDVSA 수출 중단"] }
  ]
};
window.SCEN = SCEN;
