<script>const THEATERS = [
  { id:"iran", name:"이란 전쟁과 호르무즈", sev:5, kind:"전면전", asof:"10/7", at:[53.6,32.2],
    view:[[42,20],[64,38]], countries:["364"], related:["784","634","414","368","512"],
    headline:"미국·이스라엘과 이란의 전쟁 8개월째. 미 해상봉쇄와 이란의 유조선 공격이 겹쳐 호르무즈 통항이 사실상 멈췄습니다.",
    metrics:[{v:"7~10척",l:"호르무즈 상업선 하루 통과 (10/6~7)",n:"평시 85척, Kpler · 7/23 이후 최저"},{v:"115척",l:"7/14 봉쇄 재개 후 미군이 회항시킨 상선",n:"9/23 미 중부사령부"},{v:"−10.1%",l:"이란 GDP (3~6월, 전년 대비)"}],
    brief:["2월 28일 미·이스라엘 공습으로 개전, 최고지도자 하메네이가 사망했습니다. 6월 해협 개방 양해각서는 항로 문제로 무너졌고, 미국은 7월 14일 대이란 해상봉쇄를 재개했습니다.",
           "10월 들어 이란이 유조선 공격을 다시 늘리고 있습니다. 그 와중에 이라크 국영 탱커사가 VLCC로 200만 배럴을 통과시키는 등 일부 선적은 뚫고 나갑니다.",
           "트럼프는 9월 말 7일 내 해협 재개방 제안을 거부했지만, 카타르 중재 접촉은 유엔총회 계기 회담 등으로 이어지고 있습니다.",
           "G7은 10월 2일 원유·경유 비축분 1억 배럴 방출을 발표했고, 미국의 항공 부문 제재로 이란 하늘길이 잇따라 끊기는 중입니다."],
    sources:[["straits.live 10/6","https://straits.live/briefs/2026-10-06"],["Trading Economics 브렌트","https://tradingeconomics.com/commodity/brent-crude-oil"],["Gulf News 봉쇄","https://gulfnews.com/world/mena/115-iran-linked-ships-redirected-us-naval-blockade-on-iran-continues-1.5006857"],["Reuters 이라크 VLCC","https://www.reuters.com/business/energy/iraq-says-it-transported-2-million-barrels-crude-through-strait-hormuz"],["위키백과 Current events","https://en.wikipedia.org/wiki/Portal:Current_events/October_2026"]] },

  { id:"ukraine", name:"러시아–우크라이나", sev:5, kind:"전면전", asof:"10/7", at:[35.5,48.9],
    view:[[22,43.5],[45,56.5]], countries:["804"], related:[],
    headline:"다섯 번째 겨울을 앞둔 장거리 타격전. 러시아는 키이우 교량·통신망을, 우크라이나는 모스크바와 정유시설을 노립니다.",
    metrics:[{v:"1,600대",l:"9/20 모스크바 일대로 날아간 우크라이나 드론"},{v:"650대",l:"10/6 모스크바행 드론",n:"모스크바 시장 발표"},{v:"4회",l:"10/1~2 키이우 남부교 피격 횟수"}],
    brief:["전선은 교착입니다. 코스티안티니우카에서는 양측 진지가 뒤섞인 시가전이 이어지고 있습니다.",
           "러시아는 키이우 남부교·북부교, 이동통신사 키이우스타 본사와 데이터센터, 과학아카데미를 잇따라 타격했습니다.",
           "10월 6일 불가리아 앞바다에서 상선 2척이 정체불명 드론에 맞아 1척이 침몰했습니다. 흑해 서부까지 해상 위험이 번졌습니다.",
           "미국은 10월 말 실무급 3자 회담을 제안했고, 젤렌스키는 UAE 등 제3국 개최에 응할 뜻을 밝혔습니다."],
    sources:[["ISW 10/6","https://www.criticalthreats.org/analysis/russian-offensive-campaign-assessment-october-6-2026"],["Al Jazeera 10/6","https://www.aljazeera.com/news/2026/10/6/ukraine-launches-major-drone-attack-on-russias-moscow-region-killing-two"],["CNBC 10/5","https://www.cnbc.com/2026/10/05/ukraine-war-russia-kyiv-putin-zelenskyy-trump.html"],["Reuters 흑해 선박","https://www.reuters.com/world/drones-strike-two-ships-bulgarias-black-sea-zone-president-2026-10-06/"]] },

  { id:"yemen", name:"예멘·홍해", sev:5, kind:"전면전", asof:"10/6", at:[45.2,15.6],
    view:[[36,10],[53,22]], countries:["887"], related:["682"],
    headline:"사우디 연합과 예멘 정부가 후티 전 지역 탈환을 내건 대공세에 들어갔습니다. 튀르키예·파키스탄 병력과 프랑스 방공망까지 합류합니다.",
    metrics:[{v:"10/5",l:"'예멘의 새벽' 작전 개시"},{v:"~38척",l:"바브엘만데브 하루 통과 (9월 중순)"},{v:"3개국",l:"사우디 지원 병력·장비 보내는 튀르키예·파키스탄·프랑스"}],
    brief:["9월 중순 후티가 해협 최협부 페림섬과 모카항을 장악하자 사우디가 해협 탈환 공세를 준비했고, 10월 5일 대통령지도위가 전면 공세를 선언했습니다.",
           "정부군은 같은 날 후티를 바브엘만데브 일대에서 밀어냈다고 밝혔지만, 후티는 전날 타이즈 남쪽 알투르바를 개전 이래 처음 장악했습니다.",
           "후티는 사우디 나즈란·지잔 공항과 카미스 무샤이트를 미사일로 노리고 있고, 사우디의 모카·타이즈 공습에서 민간인 피해가 나왔습니다.",
           "선사들은 수에즈로 조금씩 복귀하던 중이라, 해협 일대 지상전이 길어지면 재우회 가능성이 커집니다."],
    sources:[["Al Arabiya 작전 개시","https://english.alarabiya.net/News/middle-east/2026/10/05/yemen-s-alalimi-launches-operation-dawn-of-yemen-"],["Reuters 해협 공세","https://www.reuters.com/world/asia-pacific/saudis-plan-assault-houthis-break-red-sea-chokehold-2026-10-02/"],["Al Jazeera 메카 방위협정","https://www.aljazeera.com/news/2026/10/5/mecca-alliance-agrees-to-activate-collective-deterrence-measures"],["Sourcing Journal 수에즈 복귀","https://wwd.com/sourcing-journal/logistics/red-sea-return-cosco-oocl-houthis-bab-el-mandeb-suez-canal-strait-of-hormuz-1239231381/"]] },

  { id:"ethiopia", name:"에티오피아·티그라이", sev:5, kind:"전면전", asof:"10/7", at:[39.4,13.0],
    view:[[34,7.5],[44.5,16.5]], countries:["231"], related:["232"],
    headline:"정부군이 티그라이 주도 메켈레를 장악했고, 단교한 에리트레아군이 티그라이로 들어왔다는 보도. 국가 간 전쟁으로 번질 조짐입니다.",
    metrics:[{v:"10/4",l:"정부군 메켈레 장악"},{v:"7개",l:"반정부 연합 결성한 무장세력"},{v:"10/1",l:"에리트레아 단교"}],
    brief:["9월 TPLF가 공항 여러 곳을 장악하며 '방어 전쟁'을 선언했고, 정부군은 알라마타 등에 공습으로 대응했습니다.",
           "정부군은 10월 2일 아파르에서 TPLF를 밀어내고, 3일 메켈레 공항, 4일 메켈레 시내를 차례로 장악했습니다.",
           "에티오피아가 에리트레아의 TPLF 지원을 문제 삼아 대사관을 닫자 에리트레아가 단교했고, 7일 에리트레아군 진입 보도가 나왔습니다.",
           "수도 아디스아바바에서도 드론 추정 폭발이 있었고, 암하라에서는 파노 무장대가 공세 중입니다."],
    sources:[["Al Jazeera 메켈레","https://www.aljazeera.com/news/2026/10/4/government-forces-seize-capital-of-ethiopias-tigray-region-from-rebel"],["Addis Standard 에리트레아","https://addisstandard.com/eritrean-troops-reportedly-deploy-in-tigray-as-tension-with-ethiopia-escalate/"],["BBC 아디스아바바","https://www.bbc.com/news/articles/c3vgygpqky9zo"],["France 24 셰라로","https://www.france24.com/en/live-news/20261005-drone-hits-ethiopia-idp-camp-as-fears-grow-of-regional-war"]] },

  { id:"sudan", name:"수단", sev:4, kind:"고강도 분쟁", asof:"10/4", at:[30.2,13.4],
    view:[[20,8],[38,19]], countries:["729"], related:[],
    headline:"정부군이 북코르도판에서 거점을 하나씩 되찾는 동안 RSF는 엘오베이드를 드론으로 때리고 있습니다.",
    metrics:[{v:"10명",l:"10/1 엘오베이드 대학 기숙사 드론 사망자"},{v:"400명/일",l:"차드로 넘어가는 피란민 (UNHCR)"},{v:"500만",l:"귀환한 국내 피란민 (IOM)"}],
    brief:["정부군은 9월 25일 소드리, 10월 2일 알마즈룹을 탈환했다고 발표했습니다. 옴두르만–엘오베이드 축을 넓히는 흐름입니다.",
           "RSF는 엘오베이드에 드론 공격을 이어가고 있고, 남코르도판에서는 WFP 트럭이 공습에 맞아 운전자가 숨졌습니다.",
           "외교 쪽에서는 유엔총회 계기 미국·아프리카연합 첫 공동 협의가 열렸고, 미국은 부르한 장군에게 비자를 내주지 않았습니다."],
    sources:[["Al Jazeera 알마즈룹","https://www.aljazeera.com/news/2026/10/2/sudans-army-says-it-captured-rsf-stronghold-in-north-kordofan"],["Arab News 엘오베이드","https://www.arabnews.com/middle-east/drone-strikes-on-dormitory-shelter-kill-10-in-sudans-el-obeid-3004303"],["Reuters 차드 피란","https://www.reuters.com/world/africa/number-sudanese-fleeing-chad-surges-20-fold-aid-runs-dry-un-says-2026-09-"]] },

  { id:"gaza", name:"가자·서안", sev:4, kind:"고강도 분쟁", asof:"10/7", at:[34.4,31.4],
    view:[[33.8,30.8],[35.9,32.7]], countries:["275"], related:[],
    headline:"개전 3년. 휴전 체제 아래서도 하마스 지휘부 표적 공습이 이어지고, 서안에서는 정착민 습격이 잦아졌습니다.",
    metrics:[{v:"80%",l:"이스라엘군 통제 면적",n:"팔레스타인 당국 주장"},{v:"3명",l:"9/24~10/3 표적이 된 하마스 핵심 인사"},{v:"4건",l:"9/29~10/7 서안 정착민 습격 보도"}],
    brief:["하마스 재무 책임자(9/24), 알카삼 북부 사령관(9/29)이 사살됐고, 10월 3일에는 가자 지도자 알아무디를 노린 공습이 있었습니다.",
           "10월 3일 가자시티 주거 건물 공습으로 5명이 숨지는 등 휴전 위반 공습이 이어집니다.",
           "서안 잘루드·야수프 등에서 정착민 습격으로 사망자가 나오고 있습니다."],
    sources:[["Reuters 알베이크","https://www.reuters.com/world/middle-east/israel-kills-senior-hamas-commander-gaza-officials-say-2026-09-29/"],["Al Jazeera 10/3","https://www.aljazeera.com/news/2026/10/3/israeli-air-attack-on-gaza-city-apartment-kills-at-least-five"],["Al Jazeera 서안","https://www.aljazeera.com/news/2026/10/7/palestinian-killed-several-injured-in-israeli-pogrom-in-occupied-west"]] },

  { id:"afpak", name:"아프간–파키스탄", sev:4, kind:"고강도 분쟁", asof:"10/1", at:[70.5,33.6],
    view:[[62,28.5],[77,37.5]], countries:["004"], related:["586"],
    headline:"파키스탄이 국경 너머 아프간 군시설을 반복 공습하고, 탈레반 정권과 국경 교전이 이어지는 국가 간 분쟁입니다.",
    metrics:[{v:"10곳",l:"9/24 파키스탄 공습 대상 아프간 군시설"},{v:"12명",l:"9/26 데라 이스마일 칸 자폭 사망자"},{v:"9명",l:"10/1 공습 여성·아동 사망 (아프간 주장)"}],
    brief:["9월 코하트 테러 보복으로 시작된 파키스탄 공습이 드론 기지 타격, 쿠나르·헬만드 공습으로 이어졌습니다.",
           "국경 교전에서 양측 사상자 주장이 엇갈리고, 파키스탄 탈레반(TTP) 자폭 테러도 계속됩니다.",
           "카슈미르에서는 2025년 파할감 테러 배후 LeT 사령관이 사살됐습니다."],
    sources:[["Al Jazeera 10/1","https://www.aljazeera.com/amp/news/2026/10/1/afghanistan-says-nine-killed-in-pakistani-air-raids-on-kunar-helm"],["AP 9/24","https://apnews.com/article/pakistan-afghanistan-border-fighting-66402ffe6fc48608ea4c32a099774c4c/"]] },

  { id:"korea", name:"한반도", sev:3, kind:"긴장 고조", asof:"10/4", at:[127.4,39.6],
    view:[[123,33],[132,43.5]], countries:["408"], related:["410"],
    headline:"올해 16번째 탄도미사일. DMZ 지뢰 폭발로 한국군이 다친 뒤 남북 공방이 거칠어졌습니다.",
    metrics:[{v:"16회",l:"2026년 탄도미사일 발사 (10/3까지)"},{v:"700km+",l:"합참 발표 비행거리",n:"북한 주장 1,000km"},{v:"3명",l:"DMZ 폭발로 다친 한국군"}],
    brief:["10월 3일 원산 일대에서 발사했고, 북한은 저고도에서 궤도를 바꾸는 AI 극초음속 IRBM이라고 주장했습니다.",
           "국방장관은 9월 29일 DMZ 폭발 두 건이 북한 지뢰 때문일 가능성이 높다고 밝혔고, 북한은 이를 부인했습니다.",
           "우크라이나가 포로로 잡은 북한군 2명을 한국으로 넘겼습니다(9/23)."],
    sources:[["NK News","https://www.nknews.org/2026/10/north-korea-fires-ballistic-missile-toward-east-sea/"],["RFI DMZ","https://www.rfi.fr/en/international-news/20260929-north-korean-dmz-landmine-blasts-violation-of-armistice-seou"],["UPI 북한군 포로","https://www.upi.com/Top_News/World-News/2026/09/24/korea-Volodymyr-Zelensky-North-Korean-POWs-sent-South-Korea"]] },

  { id:"lebanon", name:"레바논·시리아", sev:3, kind:"불안한 휴전", asof:"10/3", at:[35.9,33.9],
    view:[[33.8,32],[39.5,36.8]], countries:["422"], related:["760"],
    headline:"4월 16일부터 이스라엘–레바논 휴전이 연장돼 왔지만, 이스라엘군은 남부 '안보지대'를 점령 중입니다. 시리아에서는 총격 사건이 잇따릅니다.",
    metrics:[{v:"4/16",l:"휴전 발효"},{v:"6/3",l:"휴전 이행 합의 (워싱턴)"},{v:"7명",l:"9/30 홈스 버스 총격 사망"}],
    brief:["헤즈볼라는 6월 합의를 거부하며 전면 철수를 요구했고, 이후에도 휴전 위반 공방이 반복됐습니다.",
           "유엔 평화유지군(UNIFIL)은 2026년 말 임무가 끝납니다.",
           "이 스냅숏에서는 10월 레바논 교전 기록이 확인되지 않았습니다. 시리아 홈스·라스 알마아라에서 무장 총격이 있었습니다."],
    sources:[["Armenpress 휴전 이행","https://armenpress.am/en/article/1251929/amp"],["Middle East Eye 홈스","https://www.middleeasteye.net/news/syria-hit-gas-explosion-deadly-bus-attack-and-israeli-shelling"]] },

  { id:"sahel", name:"사헬·서아프리카", sev:3, kind:"긴장 고조", asof:"10/7", at:[0.5,16.0],
    view:[[-12,8],[16,22]], countries:["466"], related:["562","854","566"],
    headline:"말리군과 러시아 아프리카군단이 다섯 달 만에 키달을 되찾았습니다. 니제르에서는 IS 공격으로 군인 50여 명이 희생됐습니다.",
    metrics:[{v:"10/7",l:"키달 탈환"},{v:"50명+",l:"9월 말 니제르 보안군 희생 (두 차례)"},{v:"18명",l:"10/2 보코하람 마르테 습격 사망"}],
    brief:["4월 JNIM·FLA 공세로 넘어갔던 키달을 공습과 지상작전 끝에 정부군이 탈환했습니다.",
           "니제르 틸라베리·타우아에서 IS가 헌병과 군을 잇달아 매복 공격했습니다.",
           "나이지리아 보르노에서는 보코하람이, 케비에서는 종족 충돌이 인명 피해를 냈습니다."],
    sources:[["Al Jazeera 키달","https://www.aljazeera.com/amp/news/2026/10/6/tuareg-rebels-withdraw-from-strategic-town-of-kidal-in-northern-m"],["Reuters 니제르","https://www.reuters.com/world/africa/more-than-50-members-nigers-security-forces-killed-attacks-sources-say-20"]] },

  { id:"drc", name:"콩고 동부·에볼라", sev:3, kind:"긴장 고조", asof:"10/6", at:[28.9,-1.4],
    view:[[20,-10],[40,4]], countries:["180"], related:[],
    headline:"M23이 고마를 쥔 채 협상은 제자리. 분디부교형 에볼라가 케냐 나이로비까지 번졌습니다.",
    metrics:[{v:"10/6",l:"케냐 첫 에볼라 유입 확진"},{v:"9/22",l:"벨기에–르완다 국교 회복"}],
    brief:["콩고는 9월 20일 현장 인력 백신 접종을 시작했지만, 콩고를 다녀온 남성이 나이로비에서 숨진 뒤 확진됐습니다.",
           "카타르 중재 직접 협상은 미타결이고, 벨기에와 르완다는 콩고 분쟁으로 끊었던 관계를 복원했습니다."],
    sources:[["Reuters 케냐 에볼라","https://www.reuters.com/business/healthcare-pharmaceuticals/kenya-confirms-first-ebola-case-imported-congo-pat"],["Reuters 벨기에–르완다","https://www.reuters.com/world/africa/belgium-rwanda-resume-diplomatic-relations-after-drc-conflict-dispute-202"]] },

  { id:"bio", name:"시베리아 페스트·보건안보", sev:3, kind:"긴장 고조", asof:"10/7", at:[104.3,52.3],
    view:[[85,40],[125,62]], countries:["496"], related:["643"],
    headline:"이르쿠츠크 항페스트연구소 연구원이 폐렴으로 숨진 뒤 약 200명이 격리됐습니다. 러시아는 '원인불명 폐렴'이라 하지만 WHO·미국은 사인 확인을 요구합니다.",
    metrics:[{v:"~200명",l:"격리·의료관찰 접촉자 (10/5)",n:"병원 4곳 봉쇄, 연구소 직원 60여 명 건물 내 격리"},{v:"10/2",l:"연구원 사망 (셸레호프 병원)",n:"9/25 시험관 파손 보도, 9/29 중증 폐렴 입원"},{v:"90%+",l:"접촉자 관찰 완료 (10/7, 로스포트레브나드조르)",n:"코로나 2·리노바이러스 2 외 검출 없음 주장"},{v:"낮음",l:"한국 국내 유입 위험 (질병청 10/7)",n:"긴급 위험평가, 변화 시 검역 즉시 강화"}],
    brief:["지역 독립매체 '류디 바이칼라'는 9월 25일 연구원이 폐페스트균 시험관을 깼다고 보도했고, 그는 9월 29일 중증 폐렴으로 입원해 10월 2일 새벽 숨졌습니다. 당국은 10월 4일 사인을 '원인불명 폐렴'으로 발표하고 업무 관련 미생물은 검출되지 않았다고 했습니다.",
           "접촉자 약 200명이 격리·관찰됐고 이르쿠츠크 병원 여러 곳이 봉쇄됐습니다. 10월 6일 러시아는 WHO에 '이르쿠츠크에 페스트 사례 없음'을 통보했고, 10월 7일 '역학적 위험 없음'을 선언했습니다. 백악관·CDC는 감시 중이며, 질병관리청은 국내 위험을 낮음으로 평가했습니다.",
           "부랴티아 자연 발생 연계설은 부랴티아 주지사가 부인했습니다. 몽골 호브드주에서는 7월 25일 마멋 섭취에 의한 선페스트 확진이 있었고, 몽골 21개 주 중 17개가 페스트 위험지역입니다."],
    sources:[["Reuters/NBC 접촉자 검사","https://www.nbcnews.com/world/russia/russia-says-no-plague-found-contacts-siberian-lab-worker-died-rcna601805"],["UN News WHO 입장","https://news.un.org/en/story/2026/10/1168533"],["CNN 격리 상황","https://edition.cnn.com/2026/10/04/europe/russia-laboratory-plague-accident-intl"],["RFE/RL 연구소 격리","https://www.rferl.org/a/russia-plague-warning-siberia-irkutsk-laboratory/33870385.html"],["Atlantic Council 5가지 쟁점","https://www.atlanticcouncil.org/dispatches/five-things-to-know-about-the-death-at-russias-anti-plague-laboratory/"],["머니투데이 질병청","https://www.mt.co.kr/thebio/2026/10/07/2026100716061638462"],["TASS 로스포트레브나드조르","https://tass.com/society/2198859"]] },

  { id:"somalia", name:"소말리아·아덴만", sev:3, kind:"긴장 고조", asof:"9/29", at:[45.3,5.0],
    view:[[40,-2],[53,13]], countries:["706"], related:[],
    headline:"바이도아에서 대통령 측과 전 남서부주 지도자 세력이 충돌. 해적이 10여 년 만에 선원을 살해했습니다.",
    metrics:[{v:"23명+",l:"9/28 바이도아 교전 사망"},{v:"5명",l:"유조선 아너25호에서 해적이 살해한 선원"}],
    brief:["헌정 위기 속에 남서부주 수도 바이도아에서 자폭 차량과 드론까지 동원된 교전이 벌어졌습니다.",
           "푼틀란드 해경이 피랍 유조선 두 척을 구출했지만, 아너25호 선원 5명이 숨졌습니다. 아덴만 해적 위험이 다시 커졌습니다."],
    sources:[["Garowe Online","https://www.garoweonline.com/en/news/somalia/heavy-fighting-erupts-in-somalia-s-baidoa-as-rival-south-west-for"],["Al Jazeera 해적","https://www.aljazeera.com/amp/news/2026/9/30/somali-pirates-killed-five-crew-members-on-hijacked-tanker-offici"]] },

  { id:"myanmar", name:"미얀마", sev:3, kind:"긴장 고조", asof:"9/28", at:[94.5,21.0],
    view:[[90,15],[100,26]], countries:["104"], related:[],
    headline:"군부가 아라칸군 장악 지역 시장을 공습해 50명 이상이 숨졌습니다.",
    metrics:[{v:"50명+",l:"9/28 짜욱토 시장 공습 사망"},{v:"58명",l:"부상"}],
    brief:["라카인주 짜욱토는 아라칸군이 장악한 곳으로, 군부 공습이 민간 시장에 떨어졌습니다."],
    sources:[["France 24","https://www.france24.com/en/live-news/20260929-myanmar-airstrike-toll-hits-50-as-families-gather-dead"]] },

  { id:"taiwan", name:"대만해협·동중국해", sev:2, kind:"회색지대", asof:"10/4", at:[121.0,23.7],
    view:[[114,19],[128,28.5]], countries:["158"], related:[],
    headline:"국경절 반짝 증가 뒤 진정. 미·중 정상회담 이후 공중 압박은 줄었지만 해상 회색지대 활동은 꾸준합니다.",
    metrics:[{v:"49대",l:"PLA 항공기 (9/28~10/4)",n:"전주 37대"},{v:"45척",l:"PLA 함정 (같은 주)"},{v:"$300억",l:"9/25 미·중 관세 인하 대상"}],
    brief:["10월 1일 23대가 나타나 16대가 중간선을 넘었지만, 이후 6대, 5대, 0대로 줄었습니다.",
           "대만은 남중국해 둥사(프라타스)에 순찰정을 상주시켰고, 중국 조사선은 일본 이시가키 인근 EEZ에서 무단 조사 뒤 퇴거했습니다.",
           "시진핑 방미 중 미·중은 관세 인하와 AI 대화 채널에 합의했습니다."],
    sources:[["Taiwan Radar","https://taiwanradar.substack.com/p/taiwan-enters-election-season"],["대만 국방부","https://www.mnd.gov.tw/en/news/plaact/87905"],["Reuters 미·중 합의","https://www.reuters.com/world/china/china-us-agree-30-billion-tariff-cut-ai-dialogue-during-xi-visit-2026-09-2"]] },

  { id:"scs", name:"남중국해", sev:2, kind:"회색지대", asof:"10/7", at:[117.8,15.2],
    view:[[107,4],[126,22]], countries:[], related:["608"],
    headline:"스카버러 암초 인근에서 중국 J-16이 필리핀 정찰기에 위험하게 근접했습니다.",
    metrics:[{v:"10/3",l:"J-16 근접 기동"},{v:"2대",l:"조우한 중국 군용기"}],
    brief:["필리핀 공군 C-208이 스카버러 순찰 중 중국 군용기 2대와 조우했습니다.",
           "필리핀 해경은 미국 지원으로 장거리 정찰기를 들여와 루손해협까지 감시를 넓힐 예정입니다."],
    sources:[["Maritime News 10/7","https://marnewssa.substack.com/p/maritime-news-07-october-2026"]] },

  { id:"carib", name:"카리브해·중남미", sev:2, kind:"회색지대", asof:"10/4", at:[-73.5,15.5],
    view:[[-86,7],[-60,22]], countries:[], related:["862","332"],
    headline:"미군의 마약선 공습(서던 스피어 작전)이 계속되고, 아이티·콜롬비아에서는 무장조직 폭력이 거셉니다.",
    metrics:[{v:"4명",l:"10/4 카리브해 선박 공습 사망"},{v:"11명+",l:"9/28 아이티 갱단 민간인 살해"}],
    brief:["트럼프는 유엔총회에서 델시 로드리게스 베네수엘라 임시 대통령과 만났습니다.",
           "유엔 안보리는 아이티 갱단 진압군 임무를 6개월 연장했습니다.",
           "콜롬비아 산타마르타는 무장단체 보복 폭동으로 군이 투입됐습니다."],
    sources:[["AP 카리브해 공습","https://apnews.com/article/trump-cartels-military-strike-caribbean-0589ce7065bc2dea0ae719c3420f4072"],["France 24 베네수엘라","https://www.france24.com/en/live-news/20260923-trump-met-with-venezuela-s-interim-leader-at-un"]] },
  { id:"latam", name:"남미", sev:2, kind:"정치·자원", asof:"10/8", at:[-60, -20], view:[[-82, -56], [-34, 13]], countries:["076", "032", "152", "604", "068", "218", "858", "600"], related:["170", "862"], headline:"브라질 대선 1차에서 플라비우 볼소나루가 룰라를 2%p 앞섰고 10/25 결선으로 갑니다. 칠레 에스콘디다·센티넬라 구리 광산은 파업 투표를 마치고 정부 중재 중입니다.", metrics:[{"v": "47% vs 45%", "l": "브라질 1차 투표 (10/4) 볼소나루 vs 룰라", "n": "결선 10/25 · 투표율 78.9%"}, {"v": "95%", "l": "에스콘디다 감독직 파업 찬성 (10/7)", "n": "BHP 정부 강제 중재 요청 · 세계 최대 구리 광산"}, {"v": "$49.2B", "l": "칠레 1~9월 구리 수출 (+18.7%)", "n": "중앙은행 집계"}], brief:["페루 케이코 후지모리(7/28 취임)·콜롬비아 데 라 에스프리에야(8/7 취임)·칠레 카스트로 이어지는 우파 전환. 콜롬비아는 취임 다음 날 남서부 차량폭탄.", "안토파가스타 센티넬라 노조도 98.7% 파업 찬성(9/26~28), 10월 초 의무 중재 개시. 중재 실패 시 합법 파업.", "아르헨티나 밀레이는 미국과 200억 달러 통화스와프 뒤 환율 밴드제 유지 중이나 의회 과반이 없음. 인도가 중국 의존을 줄이려 남미 리튬 확보에 나섬.", "칠레 중앙은행 10/26~27 회의. AMRO는 아시아 AI 투자 급반전 시 구리·리튬 수요 급감을 경고."], sources:[["Al Jazeera 브라질 1차 투표", "https://www.aljazeera.com/news/2026/10/5/brazils-presidential-race-three-key-takeaways-from-the-first-round"], ["Rio Times 에스콘디다 파업", "https://riotimesonline.com/copper-markets-latam-wednesday-october-7-2026"], ["AP 콜롬비아 취임·차량폭탄", "https://www.ottumwacourier.com/news/national_news/a-car-bomb-attack-targets-southwest-colombia-a-day-after-conservative-president-takes-office/article_be1c1e0f-deba-521b-a2ab-366c32d32173.html"], ["Rio Times 인도–남미 리튬", "https://www.riotimesonline.com/india-latin-america-lithium-copper-2026/"]] },
  { id:"namerica", name:"북미 (미국·캐나다·멕시코)", sev:3, kind:"무역·정치", asof:"10/8", at:[-100, 40], view:[[-130, 14], [-60, 60]], countries:["840", "124", "484"], related:[], headline:"미·캐나다 무역협상 결렬로 8/22 미국이 캐나다산 200억 달러 상당에 50% 관세, 캐나다는 9/8 보복 관세. 멕시코에는 카르텔 지상 타격 압박이 이어지고 11/3 중간선거는 하원 민주당 우세입니다.", metrics:[{"v": "50%", "l": "미국의 캐나다산 관세 (8/22, 1930년 338조 첫 발동)", "n": "와인·가구·유제품·시멘트·의류 등 약 200억 달러"}, {"v": "15~50%", "l": "캐나다 보복 관세 (9/8, C$276억)", "n": "자동차·부품·철강 50% 추가 위협 중"}, {"v": "11/3", "l": "미 중간선거", "n": "하원 민주당 우세, 상원은 아이오와·텍사스·오하이오·알래스카 박빙"}], brief:["트럼프는 해상 작전에 이어 '육상 타격'을 예고했고, 셰인바움은 정보 공유는 받되 외국군 작전은 불허한다고 재확인. CNN은 CIA가 멕시코 내 카르텔 작전에 직접 참여했다고 보도(5월).", "시날로아 카르텔·CJNG는 외국테러조직(FTO), 펜타닐 전구체는 대량살상무기로 지정. 시날로아 주지사 등 모레나 소속 10명 미국 기소 → USMCA 공동검토 압박 카드.", "연방정부 임시예산은 12/11까지. 트럼프 지지율은 최저 수준, 이란 전쟁·관세·유가가 선거 쟁점.", "세계은행은 관세·USMCA 불확실성으로 멕시코 2026년 성장률 1% 미만 전망."], sources:[["Bloomberg 캐나다 50% 관세", "https://news.bloomberglaw.com/tariff-news/us-canada-trade-talks-collapse-triggering-trumps-50-tariffs"], ["Baker McKenzie 캐나다 보복 관세", "https://globalimportblog.bakermckenzie.com/2026/08/26/canada-announces-new-counter-tariffs-following-suspension-of-canada-u-s-trade-negotiations/"], ["Mexico News Daily 주권 논쟁", "https://mexiconewsdaily.com/news/mexico-week-in-review-sovereignty-boiling-point/"], ["CSIS 시날로아 주지사 기소와 USMCA", "https://www.csis.org/analysis/sinaloa-governor-indicted-usmca-cartels-and-future-us-mexico-trade"], ["NPR 중간선거 전망", "https://www.wamc.org/2026-09-08/the-2026-midterm-general-election-season-is-upon-us-heres-what-to-watch"]] },
  { id:"oceania", name:"호주·태평양 도서", sev:2, kind:"전략경쟁·자원", asof:"10/8", at:[145, -18], view:[[110, -45], [180, 0]], countries:["036", "554", "598", "090", "242", "548", "776", "882"], related:[], headline:"호주는 파푸아뉴기니(2025.10)·피지(2026.7) 상호방위조약에 이어 솔로몬제도와 약 10억 달러 패키지의 포괄 조약을 협상 중입니다. 중국 국영 구매사 CMRG의 철광석 가격 압박이 구조적 위험입니다.", metrics:[{"v": "2건", "l": "호주 첫 공식 동맹조약 (1951 ANZUS 이후)", "n": "PNG·피지 · 통가·솔로몬 추진"}, {"v": "~$1B", "l": "솔로몬 조약 유인 패키지 (9/8 유출)", "n": "무상교육·치안·선거구 보조금"}, {"v": "20%", "l": "호주 상품 수출 중 대중국 철광석 비중", "n": "CMRG가 가격 결정 방식 변경 압박"}], brief:["팔라우 태평양도서국포럼(PIF)은 정상 다수 불참과 대만 외교부장 참석에 대한 중국 항의로 빛이 바램. 보건빌 독립 문제는 PNG 의회 논의 대기.", "AUKUS: 서호주 HMAS 스털링에 2027년부터 미 버지니아급 4척 배치. 중국은 군비경쟁 유발이라고 반발.", "호주 정부는 CMRG가 중기적으로 벤치마크 가격을 끌어내릴 수 있다고 경고(7월). 포테스큐 이익 40% 급감. LNG는 $16/MMBtu 상회 전망.", "솔로몬 와레 총리에 대한 불신임안은 상정 후 철회. 중국과의 안보협정은 재검토 중."], sources:[["Inside Story 호주의 태평양 안보 경쟁", "https://insidestory.org.au/australias-security-race-in-the-south-pacific/"], ["Semafor 솔로몬 조약", "https://www.semafor.com/article/09/08/2026/australia-deepens-pacific-ties-to-guard-against-china"], ["NIT 솔로몬 조약 10억 달러", "https://nit.com.au/08-09-2026/26359/free-education-in-1b-sweetener-for-solomons-treaty"], ["Mining Weekly CMRG 가격 위험", "https://www.miningweekly.com/article/australia-flags-risk-to-iron-ore-price-from-china-state-buyer-2026-07-03"], ["USNI 서태평양 동향 10/2", "https://news.usni.org/2026/10/02/usni-news-western-pacific-pulse-oct-2-2026"]] },
  { id:"europe", name:"유럽·발트해·북극", sev:3, kind:"회색지대", asof:"10/8", at:[22, 60], view:[[-10, 45], [60, 80]], countries:["246", "752", "233", "428", "440", "616", "208", "578", "276", "250"], related:["826", "528", "056", "643"], headline:"러시아 그림자함대가 발트해와 북극항로(NSR) 양쪽에서 늘고 있습니다. 우크라이나의 우스트루가·프리모르스크 타격 뒤 에스토니아 바인들로 정박지에 유조선 30~40척이 대기 중이고, NSR에는 올해 두 달 만에 2025년 한 해보다 많은 제재 유조선이 지나갔습니다.", metrics:[{"v": "50+18척", "l": "NSR 그림자 유조선·LNG선 (시즌 개시~9월 중순)", "n": "2025년 전체 38+13척 · Bellona"}, {"v": "30~40척", "l": "바인들로 정박 대기 유조선", "n": "우스트루가·프리모르스크 피격 후 3배"}, {"v": "670+", "l": "EU 제재 그림자함대 선박 (7/23)", "n": "칼리닌그라드 GPS 교란 안테나 36기(5/26)"}], brief:["NATO 발틱 센트리(2025.1)·이스턴/아크틱 센트리로 상시 감시. 러시아는 2025.5부터 군용기·군함으로 그림자함대 호위.", "NSR 그림자 선박 대부분 선령 15년 이상·저빙급으로 쇄빙 지원 없이는 운항 위험. 아시아행 선적 증가.", "EU는 하반기 최대 800억 유로 채권 발행(우크라이나 지원). 유가 상한 자동조정은 2027.7까지 유예, 2022년 이전 장기 러시아 LNG 계약도 2027.7까지 예외.", "프랑스는 그림자함대 위반 벌금·형량 2배, 마크롱은 2027년 정계 은퇴 예고. 독일·프랑스는 제재 유지+대러 관여, 동유럽은 반대."], sources:[["gCaptain NSR 그림자함대 급증", "https://gcaptain.com/shadow-fleet-traffic-on-northern-sea-route-surges-as-arctic-safety-concerns-grow/"], ["Bellona NSR 유조선 집계", "https://etc.bellona.org/2026/09/25/shadow-tankers-summer-autumn-2026/"], ["발트해 안보 트래커", "https://www.grosswald.org/baltic-sea-security-tracker/"], ["The Hill NATO 발트해 동행", "https://thehill.com/policy/defense/5516784-russian-shadow-fleet-baltic/"]] },
  { id:"southasia", name:"남아시아 (인도·방글라데시·스리랑카)", sev:2, kind:"긴장", asof:"10/8", at:[80, 22], view:[[66, 4], [96, 36]], countries:["356", "050", "144", "524", "462"], related:["586"], headline:"방글라데시 BNP 신정부(타리크 라흐만) 출범 뒤 인도–방글라데시 관계가 냉각됐고, 통제선(LoC)에서는 올해 첫 교전 보도가 나왔으나 공식 확인은 없습니다.", metrics:[{"v": "1건(미확인)", "l": "2026년 LoC 교전 보도", "n": "2021년 휴전 복원 이후 장기 소강 끝"}, {"v": "3/12", "l": "방글라데시 13대 의회 개원", "n": "BNP 압승 · 인도는 하원의장 파견"}, {"v": "3개국", "l": "인도 연계 사이버 공작 표적 (SloppyLemming)", "n": "파키스탄·방글라데시·스리랑카 정부망 · Arctic Wolf 귀속"}], brief:["인도–파키스탄은 긴장 지속되나 양측 모두 확전 회피 전망. 파키스탄은 유엔에서 '일방적 군사행동' 경고.", "스리랑카는 사이클론 디트와 복구 중, IMF 피해 평가단 파견. 미얀마 내전 유출이 방글라데시 치안 부담.", "T20 월드컵(스리랑카)에 인도–파키스탄 경기 최고 경비. 하시나 송환·크리켓 보이콧이 인도–방글라데시 마찰 소재."], sources:[["The Record 사이버 공작", "https://therecord.media/india-pakistan-cyber-campaign-apt"], ["Foreign Policy 인도–방글라데시", "https://foreignpolicy.com/2026/01/07/india-bangladesh-tensions-cricket-hasina-modi-elections/"], ["GIS 남아시아 불안", "https://www.gisreportsonline.com/r/unrest-south-asia/"]] }
];
